import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthSessionProvider from '@/components/auth-session/authSessionProvider';
import { getServerSession } from 'next-auth';
import authOptions from './api/auth/[...nextauth]/authOptions';
import Layout from '@/components/layout/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <AuthSessionProvider session={session}>
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </AuthSessionProvider>
    </html>
  );
}
